src/Promise.php, src/RejectionException.php, tests/PromiseTest.php, tests/RejectionExceptionTest.php
Added a `RejectionException` class that allows you to reject a promise with a non-string value in a safe way.
=> Added RejectionException

composer.json, src/functions.php, src/functions_include.php
The solution currently being used for conditionally autoloading functions does not work: PHP will attempt to load the functions before the conditional is evaluated. React had a similar problem (see reactphp/promise#25) which which was solved using a shim `functions_include.php` file that checks for the existence of the first function within `functions.php` before including `functions.php`. This PR modifies the conditional require to use React's method.
=> Fix conditionally requiring functions.php

src/EachPromise.php, tests/EachPromiseTest.php
Currently, creating an instance of `EachPromise` with an empty iterator will cause a `RejectionException` to be thrown with the following message: "The promise was rejected with reason: Invoking the wait callback did not resolve the promise." This PR changes that behavior so that such promises are simply resolved as no-ops.
=> Immediately resolve each promises that are passed an empty iterator

src/Promise.php, tests/PromiseTest.php
When calling `wait` on promise, a consumer can choose to forgo unwrapping. Currently, this means both that exceptions are not thrown and that inner promises are not themselves unwrapped. I'm not sure if this is the right approach, but there should be a way to wait on outstanding promises without converting failed promises into exceptions.
=> Allow recursive waiting without unwrapping exceptions

src/TaskQueue.php
Some IDEs signal a warning on executing `$task()` when not explicitly hinting `$task` as `callable`.
=> phpdoc var hint

src/EachPromise.php, tests/EachPromiseTest.php
This pull requests adds a lock around advancing the iterator given to EachPromise. This prevents a generator from recursing onto itself.
Related to https://github.com/aws/aws-sdk-php/issues/917
Probably closes https://github.com/guzzle/guzzle/issues/1412
@jeskew
=> Adding a mutex lock when advancing the iterator

src/EachPromise.php, src/FulfilledPromise.php, src/Promise.php, src/RejectedPromise.php, src/functions.php
This is a great promises library, but there are issues using it in PHP7 right now as `\Error`s are not handled by the library (the base error class in PHP7 is `\Throwable`, not `\Exception` as in PHP5). This PR simply adds support for rejecting promises with errors which inherit from `\Error` and not `\Exception`. This PR is backwards-compatible.
=> Handle \Throwable in the same way as \Exception

src/functions.php
The phpdoc return type for `each_limit` and `each_limit_all` in now correctly Promise
=> Fix return type in each_limit and each_limit_all

src/TaskQueue.php, src/TaskQueueInterface.php, src/functions.php
In order to enable efficient integrations with reactors, it would be very helpful to be able to provide a custom task queue.
Here's a simple example of what would be possible after merging this PR:
```php
use Amp\Reactor;
use GuzzleHttp\Promise\TaskQueue;
class AmpTaskQueue extends TaskQueue
{
private $reactor;
public function __construct(Reactor $reactor)
{
$this->reactor = $reactor;
}
public function add(callable $task)
{
if ($this->isEmpty()) {
$this->reactor->immediately([$this, 'run']);
}
parent::add($task);
}
}
\GuzzleHttp\Promise\queue(new AmpTaskQueue($reactor));
```
Simply calling `$reactor->immedately($task);` would really be preferable but, unfortunately, this would prevent the `run()` and `isEmpty()` methods from working as expected.
=> Make it possible to specify a new queue instance

src/Coroutine.php, src/functions.php, tests/CoroutineTest.php
Picking up #35 where @joshdifabio left off. Running through the code sample provided in that PR without this change on PHP7 causes memory usage to grow until PHP segfaults. With this change, memory holds at 6MB while running the entire coroutine.
One potential issue with this approach is the use of `wait`.
=> Fix coroutine memory leak

src/Promise.php, tests/CoroutineTest.php
`Promise\wait()` appears to be incompatible with other `PromiseInterface` implementations. This PR addresses the issue and includes a test which fails in v1.3.0 but which passes with the proposed changes. This PR should address #54 and aws/aws-sdk-php#1125.
=> Fix wait() foreign promise compatibility

src/EachPromise.php, tests/EachPromiseTest.php
The keys of iterators may not be unique, e.g. using a Generator that `yield 'foo' => 'bar'; yield 'foo' => 'baz'`.
This currently failed because the pending array would just overwrite each one. This resulted in missing Guzzle requests in our case.
=> Fix promise handling for Iterators of non-unique keys

composer.json, phpunit.xml.dist, src/EachPromise.php, tests/AggregateExceptionTest.php, tests/CoroutineTest.php, tests/EachPromiseTest.php, tests/FulfilledPromiseTest.php, tests/PromiseTest.php, tests/RejectedPromiseTest.php, tests/RejectionExceptionTest.php, tests/TaskQueueTest.php, tests/bootstrap.php, tests/functionsTest.php
- use namespaced phpunit classes
- use autoload-dev
- use ::class constant
- remove duplicate logic from #10 and #64 (they fixed the same thing in different ways)
- add test for cancelled eachpromise
=> Test cleanup

src/Promise.php
This could go either way, `If there's not a wait function` or `If there's no wait function`. I felt the second read better.
=> Grammar Fix of Inline Comment

src/functions.php
=> help code analysers not confuse each function with the deprecated php global one

src/Coroutine.php, tests/functionsTest.php
=> Reject promise instead of throwing if coroutine throws before 1st yield 

src/FulfilledPromise.php, src/Promise.php, src/RejectedPromise.php, src/functions.php
I'm sure this doesn't affect many people, but I came across this issue in an older project that uses an autoloader that in some circumstances can call `include()` without checking for file existence (relying on the class file existing somewhere in a directory defined in `include_path`).
Boiling it down, if you register a simple autoloader:
```php
spl_autoload_register(function($class) {
die($class);
});
```
Then any of the following will trigger the call to `die`:
```php
$promise = new FulfilledPromise('NotAClassName1');
```
```php
$promise = new RejectedPromise('NotAClassName2');
```
```php
$promise = promise_for('NotAClassName3');
```
```php
$promise = new Promise();
$promise->then(function() {}); // A handler must be defined to get to the relevant code …
```
=> Add explicit object checks before calling method_exists()

.travis.yml, composer.json, tests/EachPromiseTest.php, tests/functionsTest.php
This PR restores support for PHP 5.5 and HHVM 3, to match Guzzle 6.5's supported versions. I have tested against the same version of HHVM that Guzzle 6.5 tests against. After this, I think we are good to tag `v1.4.0`.
NB The hacks I added in this PR can be undone in `v2.0.0`, which will certainly drop HHVM and PHP less than 7.2.
=> Restored support for PHP 5.5 and HHVM 3

src/Utils.php, src/functions.php
`inspect_all()` simply goes over an iterable param and passes values to `inspect()` which accepts only `PromiseInterface` instances.
=> Param type fix for inspect_all()

.travis.yml
The last build of the maser branch failed with this message:
```
[Composer\Downloader\TransportException]  
Peer fingerprint did not match
```
=> Use travis_retry to mitigate random errors

src/Promise.php
Make sure we dont have a reference to the closure in the exception stack trace. 
fix https://github.com/guzzle/guzzle/issues/2606
fix https://github.com/hyperf/hyperf/issues/1486
fix #109
=> Fix memory leak

src/EachPromise.php, tests/EachPromiseTest.php
Using end() moves the internal array pointer and breaks the
iteration taking place in the promises wait function.
Use an incrementing counter to generate unique indexes for
the pending array instead.
Fixes #133
=> Use incrementing counter to generate pending indexes.
